### ISSUE TITLE
Review from XOver Team

### ISSUE THREAD

**Issue by danaylevy2004** [kar722/a1-gaming#50]
Thank you guys :D

**Comment by jm1021** [comment]
You did not link me correctly to README on pin and have video on README.   You always seem to miss the simple instructions and not get them right.   I said this would be a 1 point deduction.    The Color lab, Shift Lab were demo'd well.  It looked like Logic Gates lab had broken images and you never shared it working.   Lots of dead time in video.  I will provide you a score of 7.2/8.
