### ISSUE TITLE
Review Ticket: 10/18/21 Presentation

### ISSUE THREAD

**Issue by danaylevy2004** [kar722/a1-gaming#51]
Review Ticket for 10/18 Presentation. Leave 3 things we did well and 1 thing we could improve on.

Comments made by Daniel Levy: 8, 1 per scrum team
Comments made by Karthik Valluri: 8, 1 per scrum team
Comments made by Dylan Luo: 8, 1 per scrum team
Comments made by William Du: 8, 1 per scrum team
Total comments: 32 total comments

[Backlog 1: Photo API by Daniel L.](https://github.com/kar722/a1-gaming/issues/68)
[Backlog 2: Pop Up On Websites by Dylan L.](https://github.com/kar722/a1-gaming/issues/67)

**Comment by rkaavya** [comment]
I really like the design of your website. I also really like the different products that you display and how stylistically appealing your display is.

**Comment by DerekBokelman** [comment]
Positive: 
The page where you can see all of the computers is super cool
I love how you added multiple backgrounds, it gives the website a really cool look.
The pause button on the video was really cool and probably my favorite feature.

Things to work on: I think you guys could work on the how its made page. Yu could possibly add a background or something of that matter to make it more visually interesting.

**Comment by Tyler929** [comment]
Backgrounds look visually appealing and make the interface more user-friendly. Minilabs/technicals you showed look very cool + intriguing. Although the backgrounds + UI of the main website pages look very nice, the theme is inconsistent after navigating through some of the minilab pages.

**Comment by YashShah138** [comment]
The home page background is very appealing and interesting, I think you could add some consistency throughout your project

**Comment by tonyhieu** [comment]
There is a lot of content and pictures on your website which I like. I feel like it might be a little difficult to navigate, though; consider adding more links to the navbar

**Comment by Isaac-Le** [comment]
I like the idea of the website of giving people a place to get electrical devices, and i like the way you have showed that but if you could add more technicals to some certain pages I think would make the page much better.

**Comment by AD1616** [comment]
Layout of different pages are clean, but it would be cool to use an API instead of just pictures; I like the hardware button for the PC's. The playstation video is nice with a pause button. Incorporation of grayscale is there on the xbox page, but it doesn't really make sense.

**Comment by Pitsco** [comment]
The page seems very well-designed and user-friendly with many aspects that I search for. The technical parts are very well designed and the transition throughout all the parts of the website is pretty smooth. Though, you could elaborate more on what you presented in your code and how it was made.

**Comment by ProRichyMan** [comment]
Highlights:
- I like how you included a nice theme and design to your pages and minilabs

Improvements:
- I wish you made the video page more visually appealing because it's just black and white in the background, while the rest of your site is very colorful so it doesn't match the theme

**Comment by xXAASXx** [comment]
Things that I like:
I love the design of the website where I can always see different types of technology.
The home page background was the most appealing factor.

Things that can be Improved:
There are many bland parts in the website that can easily be improved by adding more features. I think a Pop-Up of each device would make the website look great.
Add better backgrounds, all I have been seeing is just black and white backgrounds instead of cool colors and images to match the overall idea of the website.
