### ISSUE TITLE
IFV: William Du

### ISSUE THREAD

**Issue by danaylevy2004** [kar722/a1-gaming#65]
[William's Video](https://drive.google.com/drive/folders/1Kvt6jWtNms0Y0kQQfq-FIF67wME71oSD)

**Comment by jm1021** [comment]
Watched the video.   Usually you don't show troubles on video, it would be nice if you fixed it up.  Probably you did not add images to project if it did not pull.   This distracted from you talking more about code.   On Samsung page you talked a lot about CSS and using built in features for things like gray scale.  In general you are missing relationships between what you are doing and associating with CB, this was main purpose of this activity.  4.75/6

**Comment by jm1021** [comment]
I see you understood requirements of video from comments.  However, when we give comments it is supposed to lead to additional conversation and collaboration.  You are somewhat direct to checkbox but not to general purpose in comments.   1.5/2
